/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const NHead: typeof import('next/head')['default']
  const NImage: typeof import('next/image')['default']
  const NLink: typeof import('next/link')['default']
  const NScript: typeof import('next/script')['default']
  const useSWR: typeof import('swr')['default']
}
